[book]
authors = ["siriux"]
language = "en"
multilingual = false
src = "."
title = "WishSalad Book"

[build]
build-dir = "../../wishsalad.github.io/book"
create-missing = false

[output.html]
no-section-label = true

[output.html.fold]
enable = true
level = 2
